### ISSUE TITLE
เเปดหาย น้องชาย

### ISSUE THREAD

**Issue by 1TurnKill** [boon4681/numbaht#2]
![unknown](https://user-images.githubusercontent.com/92050662/143867066-b9ac4985-c453-4c4c-9901-56b64e50dc91.png)
ตามนี้เลยท่าน

**Comment by boon4681** [comment]
ปิดครับพี่ชาย ใครใช้ให้กด enter

**Comment by boon4681** [comment]
ไม่แก้ด้วย บาย~~~
